# Generated by Django 5.0.4 on 2024-04-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.CharField(max_length=100, unique=True, verbose_name='mail'),
        ),
    ]
